### ISSUE TITLE
Cannot Enroll with a CSR Signed By a Key Stored in TPM 2.0

### ISSUE THREAD

**Issue by ZiggityZig** [certnanny/sscep#180]
As the title says. I have a piece of sotware at work that utilizes sscep and I need to add TPM integration. I have a CSR that's signed with a key stored in the TPM. The problem is that the CLI needs a path to a file where the private key is stored, only I don't have one of course since it's stored in the TPM, only a handle. I saw this discussed in https://github.com/certnanny/sscep/issues/171 as well but I see that the engine support was dropped in the latest version. So how can I go about it now? Any plans to add direct integration or Open SSL provider support?

**Comment by stv0g** [comment]
I got it working 🥳 

OpenSSL providers (in our case [tpm2-openssl](https://github.com/tpm2-software/tpm2-openssl)) can be configured via a configuration file. This configuration can be set via the `OPENSSL_CONF` environment variable.

#### `provider.cnf`

```ini
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect
alg_section = evp_properties

[evp_properties]
default_properties=

[provider_sect]
default = default_sect
legacy = legacy_sect
tpm2 = tpm2_sect

[tpm2_sect]
activate = 1

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```


#### Shell

```shell
export OPENSSL_MODULES=/var/lib/openssl/lib/ossl-modules
export OPENSSL_CONF=provider.cnf

openssl genpkey -provider tpm2 -algorithm RSA -pkeyopt bits:1024 -out local.key
openssl req -new -key local.key -subj "/C=PE/ST=Lima/L=Lima/O=Acme Inc. /OU=IT Department/CN=acme.com" -out local.csr

sscep getca -u http://localhost:8080/scep -c local.ca
sscep enroll -u http://localhost:8080/scep -c local.ca -l local.crt -k local.key-r local.csr
```

#### Output

```
sscep: sending certificate request
sscep: valid response from server
sscep: reply transaction id: 524E8D259D2F6E663407B667F958AFE0
sscep: pkistatus: SUCCESS
```


## Pitfall

I tested this against the following SCEP server implementation: https://github.com/micromdm/scep
Unfortunately, it uses DES-CBC to encrypt its responses. This appears to be hardcoded:

https://github.com/smallstep/pkcs7/blob/5e2c6a136dfaa418340bb4a7eb0d0c7421d4934c/encrypt.go#L64

This results in the following error on the client side:

```
sscep: error decrypting inner PKCS#7
40379131607F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:386:Global default library context, Algorithm (DES-CBC : 11), Properties ()
40379131607F0000:error:10800077:PKCS7 routines:PKCS7_decrypt:decrypt error:crypto/pkcs7/pk7_smime.c:518:
```

This is due to DES being a legacy cipher. After enabling the legacy provider it worked.

**Comment by hslatman** [comment]
@stv0g you could give https://smallstep.com/docs/step-ca/provisioners/#scep a try. It'll use AES if you configure it with `--encryption-algorithm-identifier 2`. I've used `sscep` myself in the past for integration testing.

Docs are _slightly_ outdated, as we also support an ECDSA signing chain, with an RSA cert just for decrypting the SCEP requests.

**Comment by stv0g** [comment]
I would argue that we can close this ticket. OpenSSL provider support does not require any modifications to sscep.

**Comment by ZiggityZig** [comment]
Hello again and thanks for the reply, much appreciated =]

I'm not sure this solves the problem. Maybe I'm missing something but I'm talking about an existing key that is stored inside the TPM. Doesn't your solution suggests that I use the TPM via OpenSSL to create a key and store it on disk?

**Comment by hslatman** [comment]
@ZiggityZig a TPM actually doesn't store the key (in most cases). In general they have very limited space for permanent objects. The way this is solved is by storing encrypted keys outside the TPM, with them only being decryptable by a specific TPM, and loaded when needed. One such format is the TSS2 PEM fotmat.

**Comment by ZiggityZig** [comment]
Yes, that's sort of what I ended up doing. But regardless of what is usually done, the original requirement was that the key remains inside the TPM and only a handle remains exposed. From what I was able to gather, this is considered to be more secure, and naturally, less flexible. So assuming there's no solution for that use case at the moment?

**Comment by hslatman** [comment]
@ZiggityZig there's no difference between loading the private key from a file, or using it directly with a handle. As long as the private key was created by the TPM (and thus not created outside, and then imported to be protected), storing the encrypted key alongside the TPM is as secure as making it a persistent key addressed by a handle, as it can only be decrypted by the TPM it was created on. 

That said, it seems possible to use `tpm2-openssl` with key handles: https://github.com/tpm2-software/tpm2-openssl/blob/master/docs/keys.md#using-key-handle. You would first have to create a key, and persist that. Then you would use the handle of the key instead of a path to a(n encrypted) key.

Note that without additional configuration, there's no actual proof of the key residing in a TPM when submitting the CSR. It depends on your use case if that's OK or not.

**Comment by ZiggityZig** [comment]
Alright. Greatly appreciating you taking the time to give me such elaborate answers, I think I have everything I need. I believe this issue can be closed.
