### ISSUE TITLE
Need HTTP/1.1 Support

### ISSUE THREAD

**Issue by oliwel** [certnanny/sscep#4]

**Comment by bartvankleef** [comment]
Is this already implemented? We currently get:
```
sscep: server returned status code 500
sscep: mime_err: HTTP/1.1 500 Internal Server Error
```

**Comment by oliwel** [comment]
HTTP/1.1 is not supported, we are working on a rewrite of the sscep tool which will support HTTP/1.1 but this is in alpha status, ETA is unknown

**Comment by bartvankleef** [comment]
Thanks, good luck with the rewrite!

**Comment by AwantikaRayzada** [comment]
I am receiving the same error in my setup when I am trying to renew using certnanny. Can I get a halp on what should I do in order to solve this problem? 
The error is as follows:
/home/admin/sscep_work/sscep_static: wrong (or missing) MIME content type
/home/admin/sscep_work/sscep_static: error while sending message

/home/admin/sscep_work/sscep_static: server returned status code 500
/home/admin/sscep_work/sscep_static: mime_err: HTTP/1.1 500 Internal Server Error
Date: Fri, 15 Sep 2017 07:56:41 GMT
Server: Apache/2.4.10 (Debian)
Connection: close
Content-Type: text/html

<h1>Software error:</h1>
<pre>I18N_OPENXPKI_CLIENT_DETACH_FAILED; __MESSAGE_FROM_SERVER__ =&gt; $VAR1 = {
          'LABEL' =&gt; 'I18N_OPENXPKI_SERVICE_SCEP_RUN_UNRECOGNIZED_SERVICE_MESSAGE'
        };
</pre>
<p>

Please help me regarding this issue. I am new to CertNanny. I need to check whether my setup is correct.
Thanks,
Awantika

**Comment by gotthardp** [comment]
The latest `develop` branch now implements a very basic (but hopefully sufficient) HTTP/1.1 support.
