### ISSUE TITLE
SCEP_OPERATION_GETCA fails

### ISSUE THREAD

**Issue by sstan** [certnanny/sscep#49]
sscep will segfault or exit with a Bus Error when the getca command is used.

The getca command seems to work if the following modifications to sscep.c are implemented.

Instead of passing c_char to PEM_write_X509, pass cacert.
https://github.com/certnanny/sscep/blob/master/sscep.c#L612

The program should exit at line 622 instead of continuing with a break. If it doesn't, pkcs7_wrap is eventually called even though it's not designed to handle a GETCA command.
https://github.com/certnanny/sscep/blob/master/sscep.c#L622

**Comment by sstan** [comment]
[fyi] I just noticed that there's a related thread: https://github.com/certnanny/sscep/issues/22

**Comment by stefankuhr** [comment]
Exactly, I stumbled across the exact same error. There seems to be another horrible bug in the code, which leads to pkcs7_wrap to be called: The stack variable scep_t is not zero initialized and I think the code is written under the assumption that scep_t is zero initialized and thus scep_t.pki_status to be zero when entering the loop. When using the getca option, the scep_t variable can contain garbage (since it is not initialized) and therefore the loop is entered that calls pkcs7_wrap with a garbage object. When compiling on Windows with Visual C this immediately crashes the process. When compiling with cygwin, it seems to be zero initialized  with zero and it works. But if I add code that initializes the scep_t stack variable with some garbage, I get the exact same crash with my cygwin based binary.

**Comment by stefankuhr** [comment]
I was unable to upload my patch file even with its extension changed to .txt, so this is my patch so far to address the various getca problems:

--- sscep.c	2015-04-16 09:00:16.000000000 +0200
+++ sscep.c.patched	2015-10-14 12:44:22.890239700 +0200
@@ -71,7 +71,7 @@
 	struct http_reply	reply;
 	unsigned int		n;
 	unsigned char		md[EVP_MAX_MD_SIZE];
-	struct scep		scep_t;
+	struct scep		scep_t= {0};
 	FILE			*fp = NULL;
 	BIO			*bp;
 	STACK_OF(X509)		*nextcara = NULL;
@@ -609,7 +609,7 @@
 					"writing\n", pname);
 				exit (SCEP_PKISTATUS_ERROR);
 			}
-			if (PEM_write_X509(fp, c_char) != 1) {
+			if (PEM_write_X509(fp, cacert) != 1) {
 				fprintf(stderr, "%s: error while writing CA "
 					"file\n", pname);
 				ERR_print_errors_fp(stderr);
@@ -619,7 +619,7 @@
 			printf("%s: CA certificate written as %s\n",
 				pname, c_char);
 			(void)fclose(fp);
-			pkistatus = SCEP_PKISTATUS_SUCCESS;
+			scep_t.pki_status = pkistatus = SCEP_PKISTATUS_SUCCESS;
 			break;
 
 		case SCEP_OPERATION_GETNEXTCA:

**Comment by stefankuhr** [comment]
uups, I should've read about the markdown syntax, here goes my patch:

```
--- sscep.c	2015-04-16 09:00:16.000000000 +0200
+++ sscep.c.patched	2015-10-14 12:44:22.890239700 +0200
@@ -71,7 +71,7 @@
 	struct http_reply	reply;
 	unsigned int		n;
 	unsigned char		md[EVP_MAX_MD_SIZE];
-	struct scep		scep_t;
+	struct scep		scep_t= {0};
 	FILE			*fp = NULL;
 	BIO			*bp;
 	STACK_OF(X509)		*nextcara = NULL;
@@ -609,7 +609,7 @@
 					"writing\n", pname);
 				exit (SCEP_PKISTATUS_ERROR);
 			}
-			if (PEM_write_X509(fp, c_char) != 1) {
+			if (PEM_write_X509(fp, cacert) != 1) {
 				fprintf(stderr, "%s: error while writing CA "
 					"file\n", pname);
 				ERR_print_errors_fp(stderr);
@@ -619,7 +619,7 @@
 			printf("%s: CA certificate written as %s\n",
 				pname, c_char);
 			(void)fclose(fp);
-			pkistatus = SCEP_PKISTATUS_SUCCESS;
+			scep_t.pki_status = pkistatus = SCEP_PKISTATUS_SUCCESS;
 			break;
 
 		case SCEP_OPERATION_GETNEXTCA: 
```

**Comment by copacetic** [comment]
your patch fixed my issue! thanks so much -_-

**Comment by tedescn** [comment]
This patch also fixes my issues. Thank you very much.

I will close my issue and point resolution at this thread.

Regards
Nigel

**Comment by mbartosch** [comment]
Fixed
