### ISSUE TITLE
What is the right way to get SAN (subject alternative names)?

### ISSUE THREAD

**Issue by Timvissers** [certnanny/sscep#69]
What is the right request to make to get subject alternative names
mkrequest -dns alias1 {{ca_enrollment_pass}} is for alias1

What is the command to get my alias2 and alias3 there? Do we need a comma? Do we need multiple times -dns? Something else?

Thanks!

**Comment by tedescn** [comment]
First, the assumption is your issuing CA must first support multiple SAN values, I don't know which Issuing CA you use but this should be based on SCEP Responder / CA configs. Typically I might test using manual enrollment first (note: some Issuing CAs support different certificate issuance profiles for manual and automation, hence this testing isn't conclusive).  

Second, the .csr attributes output would need to be of the form:

openssl req -text -noout -in <.csr file>

..
_Attributes:
  challengePassword_        :changeit!
  X509v3 Subject Alternative _Name:critical,DNS.1:m2m-iot.poc.scep.com,DNS.2:www.example1.com,DNS.3:www.example2.com,DNS.4:www.example3.com_
..

Note, if the Issuing CA doesn't support multiple SANs the additional valid SAN values may be dropped by the CA.

Regards
Nigel

**Comment by timv2** [comment]
Hi,
The CA supports multiple SAN values
I understand that the csr file needs the multiple entries.

I do not understand how I can create a csr having multiple SAN values using the mkrequest command. Is this possible?

Thx for replying!
Tim

**Comment by timv2** [comment]
Just to say, instead of using the mkrequest, I reverted to using plain openssl to generate the csr with multiple SANs. Config like this:
`[ req ]
prompt = no
distinguished_name = req_distinguished_name
attributes = req_attributes
req_extensions = req_ext
[ req_attributes ]
challengePassword={{ca_enrollment_pass}}
[ req_distinguished_name ]
CN = {{ansible_hostname}}
[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1 = {{ansible_fqdn}}
{% if loadbalancer_host is defined %}
DNS.2 = {{loadbalancer_host}}
{% endif %}`

**Comment by gotthardp** [comment]
I added a remark concerning this to the documentation.
