### ISSUE TITLE
sscep should support https connections

### ISSUE THREAD

**Issue by trevor-vaughan** [certnanny/sscep#74]
After using a few tools, it has been nice to be able to support `https` connections after being provided the CA certificate through some valid mechanism.

This is particularly true when talking to old/legacy systems that happen to be able to talk `https` but can't use `AES` ciphers.

**Comment by mbartosch** [comment]
SCEP is transported over HTTP. It does not improve security to use TLS in this context, and using TLS introduces additional problems such as trust management for the TLS Server certificate.

**Comment by trevor-vaughan** [comment]
@mbartosch I'm OK with the `wontfix`, but TLS would improve security via confidentiality but not via integrity.

That said, a bit of confidentiality against random people on your network is better than nothing (which is the current state).

**Comment by davidzech** [comment]
Wouldn't this be useful not for necessarily using TLS, but for operating under infrastructure that *only* allows TLS. It is indeed nonstandard, but seems like a harmless addition.

**Comment by achuchev** [comment]
@mbartosch I second @davidzech opinion. Even that the SCEP draft of RFC does not mandates TLS, these days many organisations require TLS no matter if the payload is encrypted or not. The restriction is done on network level. 

It is true that it will require truststore management, but there are elegant ways to solve it. You can check how this is done in https://github.com/cisco/libest

**Comment by mbartosch** [comment]
I disagree. There are other protocols for which TLS does not make sense, e. g. CRL download via HTTP and OCSP over HTTP. Demanding those protocols to be transmitted over HTTPS is asking for trouble.
Organizations that define no exceptions for sensible use of HTTP for use with cryptographic protocols have a problem that should be addressed not by working around in the implementation of software but by addressing the underlying, incorrect assumption within the environments.

I disagree that the solution implemented in libest is a good or even elegant one:
https://github.com/cisco/libest/blob/43116f6e373d030c088c20b1351f7436e070c898/src/est/est_client.c#L570
simply adds all self-signed root certificates delivered by the /cacerts operation of the EST server to the trust store and implicitly uses this for verification of further communication.

The EST RFC states that

   The client MAY
   provisionally continue the TLS handshake to completion for the
   purposes of accessing the /cacerts or /fullcmc method.  If the EST
   client continues with an unauthenticated connection, the client MUST
   extract the HTTP content data from the response (Sections 4.1.3 or
   4.3.2) and engage a human user to authorize the CA certificate using
   out-of-band data such as a CA certificate "fingerprint" (e.g., a
   SHA-256 or SHA-512 [SHS] hash on the whole CA certificate).

Out-of-band verification is not done in libest, hence the library basically blindly performs a TLS handshake "on best effort" without a properly verified trust anchor. For EST this is even more critical, as it uses the TLS handshake as an integral part of the protocol.
Since a proper trust anchor management is the core assumption of any reasonable (enrollment) protocol, I thus assume that libest might be susceptible to MITM attacks, but at the very least it violates the RFC.

If anyone feels the need to support TLS I guess the project will accept a properly crafted pull request implementing the feature. Make sure to implement proper trust management and/or only allow a libest-like behavior by explicit specification of a "--insecure" command line option or similar.

**Comment by achuchev** [comment]
@mbartosch I agree with all the things that you have explained above. 

Generally speaking, there are two main use cases when using such SCEP/EST tools:
1. In production, where the all PKI best practices must be implemented and used. This means that proper trust management is needed (incl. revocation checks)
2. For POC/testing purposes. Here the main goal is to quickly proof that the solution works even without implementing all security best practices. Here is where `--insecure` flag will fit.

Thanks for the valuable discussion.

PS: What I was pointing in the ESL library is they way to define trusted anchors using `EST_OPENSSL_CACERT` env variable.

**Comment by ajoy39** [comment]
Just wanted to bump this, I know the decision was made for "won't fix" but in 2025 a lot of organizations are implementing TLS for all connections by default rather than just adding it in cases of need. I also find myself unable to find a Linux SCEP tool that we can use with Okta, because Okta only supports HTTPS connections. Adding a TLS/HTTPS option might not increase security at all but it would increase compatibility with SCEP servers.

**Comment by mbartosch** [comment]
It is a misconception that SCEP over TLS is a viable option.

The decision was not made by the project maintainers but by the RFC authors. And rightfully so. SCEP is transported over HTTP. 
For a definitive answer see https://www.rfc-editor.org/rfc/rfc8894.html#section-7.10

Any organization that is not comfortable with this should use a different standard such as EST (RFC 7030) or simply obey the RFC.
